language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
script:
  coverage run --source=g2t setup.py test
after_success:
  coveralls